### ISSUE TITLE
执行login/getLoginQrCode时，返回“创建设备失败”

### ISSUE THREAD

**Issue by c2j** [Devo919/Gewechat#30]
重启客户端之后报这个错，即使重启gewe容器也一样报错，不懂为啥。
报错：{'ret': 500, 'msg': '创建设备失败', 'data': {'code': '-1', 'msg': "invalid character '<' looking for beginning of value"}}

**Comment by July-chen-byte** [comment]
同问  {"ret": 500,"msg": "创建设备失败"}  
我是使用的虚拟机做的容器  虚拟机网络能够正常的ping通百度地址  主机和虚拟机也可以正常通讯 就是调用login/getLoginQrCode时，返回“创建设备失败”

**Comment by July-chen-byte** [comment]
虚拟机版本为 CentOS 7

**Comment by c2j** [comment]
补充错误日志：
tail -f /root/gewe/base/log/devicelibrary.txt
{"level":"error","msg":"[SelfTestApi] 所有设备库api均不可用,正在进行下一轮检测。10秒后进行下一轮","time":"2024-11-25 15:23:35"}
{"level":"error","msg":"[/api/user/token] invalid character '\u003c' looking for beginning of value","time":"2024-11-25 15:23:46"}

**Comment by bwcx-jzy** [comment]
![image](https://github.com/user-attachments/assets/0e9cd212-c0f8-4225-8510-3ec558933e0e)

**Comment by ShanHaiYKP** [comment]
网络错误 开启vpn
 会这样，记得关

**Comment by bwcx-jzy** [comment]
现在问题是多尝试几次能正常获取到二维码，扫描后执行登录也返回成功。但是后续获取个人资料就失败。手机上也没有显示 ipad 登录，登录过的设备记录也没有 ipad

**Comment by bwcx-jzy** [comment]
和系统负载有关系吗？我是在 NAS 里面搭建的，机器负载有波动
![image](https://github.com/user-attachments/assets/ae5af464-0005-492b-b4f8-8b80e8aa3324)

**Comment by LeanFly** [comment]
> ![image](https://private-user-images.githubusercontent.com/16408873/390946674-0e9cd212-c0f8-4225-8510-3ec558933e0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODUzNjcsIm5iZiI6MTczMzI4NTA2NywicGF0aCI6Ii8xNjQwODg3My8zOTA5NDY2NzQtMGU5Y2QyMTItYzBmOC00MjI1LTg1MTAtM2VjNTU4OTMzZTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA0MDQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNDJmNzYwYzMzOTQzM2FkYWU3OTA1YjliOTY3NTRkNTUxNmE3N2Q4YzY1ZTJmNmJkNDAyMjY3MGZiZTIxNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZtXVnQW2wRqKNd5yl6ZV2l4nSn7hMkt4Sz7TGe8hM2s)

我也遇到了相同的问题。使用tail -f /root/gewe/base/log/devicelibrary.txt 看到的日志也相同。

**Comment by LeanFly** [comment]
通过 tail -f /root/gewe/base/log/devicelibrary.txt 查看日志，在没有提示设备库api不可用的间隔期内创建设备id成功，登录成功了。

**Comment by sofs2005** [comment]
我也是创建设备失败：
http请求失败, url=http://10.6.6.11:2531/v2/api/login/getLoginQrCode, exception={"ret":500,"msg":"创建设备失败","data":{"code":"-1","msg":"invalid character '<' looking for beginning of value"}}
[ERROR][2024-12-07 14:26:47][app.py:66] - App startup failed!
[ERROR][2024-12-07 14:26:47][app.py:67] - {"ret":500,"msg":"创建设备失败","data":{"code":"-1","msg":"invalid character '<' looking for beginning of value"}}
Traceback (most recent call last):
  File "/app/lib/gewechat/util/http_util.py", line 20, in post_json
    raise RuntimeError(response.text)
RuntimeError: {"ret":500,"msg":"创建设备失败","data":{"code":"-1","msg":"invalid character '<' looking for beginning of value"}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/app.py", line 61, in run
    start_channel(channel_name)
  File "/app/app.py", line 40, in start_channel
    channel.startup()
  File "/app/channel/gewechat/gewechat_channel.py", line 59, in startup
    app_id, error_msg = self.client.login(self.app_id)
  File "/app/lib/gewechat/client.py", line 249, in login
    return self._login_api.login(app_id)
  File "/app/lib/gewechat/api/login_api.py", line 113, in login
    app_id, uuid = self._get_and_validate_qr(app_id)
  File "/app/lib/gewechat/api/login_api.py", line 77, in _get_and_validate_qr
    qr_response = self.get_qr(app_id)
  File "/app/lib/gewechat/api/login_api.py", line 28, in get_qr
    return post_json(self.base_url, "/login/getLoginQrCode", self.token, param)
  File "/app/lib/gewechat/util/http_util.py", line 23, in post_json
    raise RuntimeError(str(e))
RuntimeError: {"ret":500,"msg":"创建设备失败","data":{"code":"-1","msg":"invalid character '<' looking for beginning of value"}}

**Comment by c2j** [comment]
周四拉到群中，经过指点，对于各种错误，只有坚持一点：不断重试。我将getLoginQrCode过程修改为检测返回结果，如果不对就过1秒重试，最多1200次，肯定能过。

> 我也是创建设备失败： http请求失败, url=http://10.6.6.11:2531/v2/api/login/getLoginQrCode, exception={"ret":500,"msg":"创建设备失败","data":{"code":"-1","msg":"invalid character '<' looking for beginning of value"}} [ERROR][2024-12-07 14:26:47][app.py:66] - App startup failed! [ERROR][2024-12-07 14:26:47][app.py:67] - {"ret":500,"msg":"创建设备失败","data":{"code":"-1","msg":"invalid character '<' looking for beginning of value"}} Traceback (most recent call last): File "/app/lib/gewechat/util/http_util.py", line 20, in post_json raise RuntimeError(response.text) RuntimeError: {"ret":500,"msg":"创建设备失败","data":{"code":"-1","msg":"invalid character '<' looking for beginning of value"}}
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/app/app.py", line 61, in run start_channel(channel_name) File "/app/app.py", line 40, in start_channel channel.startup() File "/app/channel/gewechat/gewechat_channel.py", line 59, in startup app_id, error_msg = self.client.login(self.app_id) File "/app/lib/gewechat/client.py", line 249, in login return self._login_api.login(app_id) File "/app/lib/gewechat/api/login_api.py", line 113, in login app_id, uuid = self._get_and_validate_qr(app_id) File "/app/lib/gewechat/api/login_api.py", line 77, in _get_and_validate_qr qr_response = self.get_qr(app_id) File "/app/lib/gewechat/api/login_api.py", line 28, in get_qr return post_json(self.base_url, "/login/getLoginQrCode", self.token, param) File "/app/lib/gewechat/util/http_util.py", line 23, in post_json raise RuntimeError(str(e)) RuntimeError: {"ret":500,"msg":"创建设备失败","data":{"code":"-1","msg":"invalid character '<' looking for beginning of value"}}

**Comment by Devo919** [comment]
> 周四拉到群中，经过指点，对于各种错误，只有坚持一点：不断重试。我将getLoginQrCode过程修改为检测返回结果，如果不对就过1秒重试，最多1200次，肯定能过。
> 
> > 我也是创建设备失败： http请求失败, url=http://10.6.6.11:2531/v2/api/login/getLoginQrCode, exception={"ret":500,"msg":"创建设备失败","data":{"code":"-1","msg":"invalid character '<' looking for beginning of value"}} [ERROR][2024-12-07 14:26:47][app.py:66] - App startup failed! [ERROR][2024-12-07 14:26:47][app.py:67] - {"ret":500,"msg":"创建设备失败","data":{"code":"-1","msg":"invalid character '<' looking for beginning of value"}} Traceback (most recent call last): File "/app/lib/gewechat/util/http_util.py", line 20, in post_json raise RuntimeError(response.text) RuntimeError: {"ret":500,"msg":"创建设备失败","data":{"code":"-1","msg":"invalid character '<' looking for beginning of value"}}
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "/app/app.py", line 61, in run start_channel(channel_name) File "/app/app.py", line 40, in start_channel channel.startup() File "/app/channel/gewechat/gewechat_channel.py", line 59, in startup app_id, error_msg = self.client.login(self.app_id) File "/app/lib/gewechat/client.py", line 249, in login return self._login_api.login(app_id) File "/app/lib/gewechat/api/login_api.py", line 113, in login app_id, uuid = self._get_and_validate_qr(app_id) File "/app/lib/gewechat/api/login_api.py", line 77, in _get_and_validate_qr qr_response = self.get_qr(app_id) File "/app/lib/gewechat/api/login_api.py", line 28, in get_qr return post_json(self.base_url, "/login/getLoginQrCode", self.token, param) File "/app/lib/gewechat/util/http_util.py", line 23, in post_json raise RuntimeError(str(e)) RuntimeError: {"ret":500,"msg":"创建设备失败","data":{"code":"-1","msg":"invalid character '<' looking for beginning of value"}}

？？？   什么鬼，我测试正常啊。。。

**Comment by nishubin** [comment]
问题解决了吗？我也遇到了类似的问题

**Comment by rogerc66** [comment]
+1

**Comment by mrzxc** [comment]
+1

**Comment by zengxianming01** [comment]
{
	"ret": 500,
	"msg": "获取二维码失败",
	"data": {
		"code": "-1",
		"msg": "设备环境存在异常,请重新尝试"
	}
}


返回这个报错可能是哪些原因

**Comment by DT-stone** [comment]
提示: {"ret":500,"msg":"创建设备失败","data":{"code":"-1","msg":"exceeded maximum retries"}}

查看容器日志:tail -f /root/gewe/base/log/devicelibrary.txt
显示:
{"level":"error","msg":"[/api/wxsdk/getdeviceinfo] The current token has expired","time":"2025-03-12 22:01:59"}


可是 token 再怎么获取,似乎一直没变化

**Comment by LiJinHao999** [comment]
我也遇到了此问题，但我自行解决了。
这里提供一种可能：可能机器上网络的DNS有些问题，没有正确解析微信的域名
可以先尝试在容器内ping www.baidu.com看看有没有反应。

**Comment by jiahao6635** [comment]
{"ret":500,"msg":"创建设备失败","data":{"code":"-1","msg":"exceeded maximum retries"}}
